version: "3.8"
services:
  db:
    image: "postgres:12.8"
    ports:
      - "5440:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=pizza
